# Generated by Django 5.0.1 on 2024-02-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_par_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='par',
            name='rsrTime',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='par',
            name='swimTime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
