# Generated by Django 5.0.1 on 2024-02-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_par_rsrtime_alter_par_swimtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='par',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='par',
            name='rsrPts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='par',
            name='swimPts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
