# Generated by Django 5.0.1 on 2024-02-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_par_rank_par_rsrpts_par_swimpts'),
    ]

    operations = [
        migrations.AddField(
            model_name='par',
            name='totalPts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
